




function setup() {
  //creats a canvas of size 600 X 600 pixels.
  createCanvas(1920, 1080);
  //creates a bg of black colour
  background(0);
}

function draw() {
  let STROKE_RED = random(255);
  let STROKE_GREEN = random(255);
  let STROKE_BLUE = random(255);

  let CIRCLE_DIAMETER = random(100);
  //does not fill the shape
  fill(0);
  //sets up the stroke as random colour
  stroke(STROKE_RED, STROKE_GREEN, STROKE_BLUE);
  //creates a circle that mouses based
  //on x and y positions and a radius
  //generated by random()
  circle(mouseX, mouseY,CIRCLE_DIAMETER);
}
//gets called when LMB is clicked
function mouseClicked() { 

  clear(); //clears all the pixels
  setup(); 
}
