function setup() {
  //creats a canvas of size 600 X 600 pixels.
  createCanvas(600, 600);
  //creates a bg of black colour
  background(0);
}

function draw() {
  //does not fill the shape
  fill(0);
  //sets up the stroke as white colour
  stroke(255);
  //creates a circle that mouses based
  //on x and y positions and a radius
  //generated by random()
  circle(mouseX, mouseY, random(50));
}
//gets called when LMB is clicked
function mouseClicked() { 
  
  clear(); //clears all the pixels
  setup(); 
}
